### PR TITLE
update brand guidelines

### PR DESCRIPTION
**Pull request by jbottum**
updated brand guidelines to CNCF and contact to ksc@kubelfow.org.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
You may also want to update the Kubeflow website:

https://www.kubeflow.org/docs/about/community/#kubeflow-trademark

But also the current website is slightly incorrect, because I'm not aware of any jurisdictions in which the logo is a registered trademark (the wording is more correct on the readme from this PR, so perhaps we should update the Website to be more similar).

**Review by terrytangyuan — APPROVED** [review]
Thanks Josh!

/lgtm

**Comment by terrytangyuan** [comment]
Sorry seems like the merge bot didn’t see my hold on time yet. This looks good. If there are other comments, we can probably address in a follow-up PR.

**Pull request merged**
