### PR TITLE
Add Manifests WG call to common calendar

### PR DESCRIPTION
**Pull request by kimwnasptd**
This PR introduces the following changes:
1. Add the Manifests WG meeting in the common Kubeflow calendar
    * The meeting links, recording and drive are maintained by Manifests WG
    * The meeting will now be happening on a bi-weekly basis, rather than monthly
    * The meeting day will be Thursday instead of Tuesday
2. Remove the Model Management SIG call which conflicts with manifests 
    * We've given a notice 2 months ago but got no response #619 
    * The last meeting of this SIG was in 7 Feb 2021

cc @kubeflow/wg-manifests-leads @annajung @juliusvonkohout 
/assign @james-jwu

### CODE REVIEW

**Comment by kimwnasptd** [comment]
This was also discussed during the latest Manifests WG [call](https://drive.google.com/file/d/1-b3NLCSsfYeAsXpIErS-VSvdKSOCfP4I/view?usp=sharing)

**Comment by juliusvonkohout** [comment]
@kimwnasptd  the monthly "Kubeflow Feature Store SIG Meeting (US/Asia friendly)" is also dead for years AFAIK. It should be removed as well.

**Comment by johnugeorge** [comment]
/lgtm

We need to separately cleanup the entries that are no more active.

**Comment by kimwnasptd** [comment]
@james-jwu I see that the changes in the calendar were not reflected in the common calendar. I think there's a good chance we need to run some script to update. Do you have more insight in this?

**Comment by james-jwu** [comment]
There seems to be an error when syncing the calendar:

ERROR|2023-06-22T06:11:10|/usr/local/google/home/jamesjwu/dev/community.1/calendar/calendar_import.py|242| Could not update meeting kf035; Error:
time data '05/15/2023 6:00' does not match format '%m/%d/%Y %I:%M%p'
ERROR|2023-06-22T06:11:10|/usr/local/google/home/jamesjwu/dev/community.1/calendar/calendar_import.py|242| Could not update meeting kf036; Error:
time data '06/01/2023 6:00' does not match format '%m/%d/%Y %I:%M%p'

I think you need to change   "time: 6:00-7:00 PM (EET)" to "time: 6:00PM-7:00PM". The timezone needs to be specified in a separate field (see line 10 in calendar.yaml file for definition, and line 48 for an example).

Apparently I didn't know better when Amber created the calendar entry for security meeting meeting, so her meeting entry is failing for the same reason.

/cc @akgraner

**Comment by kimwnasptd** [comment]
Oh I see, thanks for exposing this! I'll send a follow-up PR to fix these discrepancies and update the README to expose this information

**Comment by akgraner** [comment]
Thanks James!

Fixing the security meeting information now.

And I'll update the Security Team README as well.

**Pull request merged**
