### PR TITLE
Update community meeting process to not rely on Zoom hosting the recording

### PR DESCRIPTION
**Pull request by ewilderj**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/59)

### CODE REVIEW

**Comment by ewilderj** [comment]
gah, I keep hitting close by accident. @ankushagarwal unfortunately I need an approver from OWNERS as well. thanks for the review!

**Comment by jlewi** [comment]
@ewilderj You can approve your own PRs once they've been lgtm'd and per our contributor guide its acceptable to do this for PRs that don't merit a 2nd review by an approve.

**Pull request merged**
