### PR TITLE
Small fixes in wg-manifests, wg-notebooks

### PR DESCRIPTION
**Pull request by yanniszark**
This PR:
- Fixes the subprojects of wg-manifests and wg-notebooks that got mixed up.
- Adds KFAM to the wg-notebooks subproject list, as described in its charter doc.

/cc @PatrickXYS @Jeffwan @jlewi @cvenets

### CODE REVIEW

**Comment by Jeffwan** [comment]
@yanniszark Thanks taking care of this. That's probably due to my rebase yesterday. There was lots of conflicts in that PR and I may not bring the up to date version. Glad you figure it out! Thanks 

/lgtm

**Comment by jlewi** [comment]
Thanks @yanniszark 

While your here: Could you please delete
https://github.com/kubeflow/community/tree/master/wgs/wg-pipelines

And rename wgs to wgs-templates

**Comment by yanniszark** [comment]
@jlewi 

> While your here: Could you please delete
> https://github.com/kubeflow/community/tree/master/wgs/wg-pipelines

Done!

> And rename wgs to wgs-templates

Are you sure? I am asking because the `wgs` folder has a subfolder called `templates`, which contains the charter template.
The other files are guides around the WGs. Unless I'm missing something?

**Pull request merged**
