### PR TITLE
Add dates to the 1.5 release timeline

### PR DESCRIPTION
**Pull request by annajung**
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>

Based on the [release team meeting on Nov. 22nd](https://docs.google.com/document/d/1Cs9XYl_SHfGP9vs1eHyqb6JAcpE3ilM-5iRuBnV9AB4/edit?usp=sharing), the release team proposes the following dates for the 1.5 release.

Important dates are outlined below:
- **Thursday, Oct 21st 2021**: Week 1 - Release Cycle Begins
- **Thursday, Jan 13th 2021**: Week 13 - Feature Freeze
- **Thursday, Jan 27th 2021**: Week 15 - Manifests Testing Starts
- **Thursday, Feb 3rd 2021**: Week 16 - Manifests Testing Ends
- **Thursday, Feb 3rd 2021**: Week 16 - Docs Update Ends
- **Friday, Feb 4th 2021**: Week 16 - Distribution Testing Starts
- **Wednesday, Feb 23rd 2021**: Week 19 - Distribution Testing Ends
- **Thursday, Feb 24th 2021**: Week 19 - Kubeflow v1.5 Released

Note: All release phases have increased 2 weeks to accommodate for the end of the year holiday season. 1.5 release will be 19 weeks instead of 17 weeks 

cc @kimwnasptd @jbottum @shannonbradshaw

### CODE REVIEW

**Comment by annajung** [comment]
/hold until review from the community

@kimwnasptd will send out an email to the mailing list to increase visibility of the proposed timeline and share during the Nov 23rd community meeting to gather feedback

**Comment by thesuperzapper** [comment]
@annajung maybe I missed it, but can you link me to where the release team for 1.5 was decided?

**Comment by kimwnasptd** [comment]
> @annajung maybe I missed it, but can you link me to where the release team for 1.5 was decided?
> For example, here was the voting issue for Kubeflow 1.4's release team:
> Kubeflow 1.4 Release Team #517

The release team went over this with the community and WGs in the 1.4 release retro https://github.com/kubeflow/community/blob/master/releases/retrospectives/release-1.4.md. We will be following what K8s does, where the leads are choosing the next leads. We've sent an email to the list as well to get more people to be part of the release, join the meetings and follow the process.

Nominations happened for 1.4 because there was no Release Team previously, but now we have both a handbook/process and defined roles.

**Comment by thesuperzapper** [comment]
> The release team went over this with the community and WGs in the 1.4 release retro https://github.com/kubeflow/community/blob/master/releases/retrospectives/release-1.4.md. We will be following what K8s does, where the leads are choosing the next leads. We've sent an email to the list as well to get more people to be part of the release, join the meetings and follow the process.

To follow up, I have raised my concerns about how this release team was formed in: https://github.com/kubeflow/community/issues/540

**Comment by kimwnasptd** [comment]
I'd like to draw the attention of the WGs to this issue and get some feedback. This is the timeline we had discussed and proposed for 1.5. What are your thoughts? Do you have any concerns?

cc @kubeflow/wg-automl-leads
cc @kubeflow/wg-deployment-leads
cc @kubeflow/wg-manifests-leads
cc @kubeflow/wg-notebooks-leads
cc @kubeflow/wg-pipeline-leads
cc @kubeflow/wg-training-leads

NOTE: Let's keep this discussion and communication in parallel with the formation of the release team, and not have one block on the other.

cc @annajung @jbottum @shannonbradshaw @DomFleischmann @DnPlas @js-ts

**Comment by thesuperzapper** [comment]
I think let's allow the new release team to decide on the dates, and not force anything on them.

**Comment by annajung** [comment]
The 1.5 release team has been [finalized](https://groups.google.com/g/kubeflow-discuss/c/KDTXp49Mk48/m/5uyBAgDACAAJ) and would like to suggest we move forward with the release timeline.

Important notes:
- All release phases have **increased by 2 weeks** to accommodate for the end of the year holiday season
- 1.5 release will be **19 weeks** instead of 17 weeks
- Proposed feature freeze is **Thursday, Jan 13th 2021**
- Proposed release day for 1.5 is **Thursday, Feb 24th 2021**

Please take a look at the proposed timeline and provide your feedback, thank you!
cc @kubeflow/wg-automl-leads @kubeflow/wg-deployment-leads @kubeflow/wg-manifests-leads @kubeflow/wg-notebooks-leads @kubeflow/wg-pipeline-leads @kubeflow/wg-training-leads

**Comment by kimwnasptd** [comment]
@yuzisun @animeshsingh @pvaneck this is our tracking issue for the 1.5 timeline. How does this sound to you?

We will finalize this schedule on Friday 17th of December and merge this PR then.

**Comment by yuzisun** [comment]
> @yuzisun @animeshsingh @pvaneck this is our tracking issue for the 1.5 timeline. How does this sound to you?
> 
> We will finalize this schedule on Friday 17th of December and merge this PR then.

@kimwnasptd We are good with the schedule, are you going to cover the KServe webapp testing?

**Comment by kimwnasptd** [comment]
> @kimwnasptd We are good with the schedule, are you going to cover the KServe webapp testing?

@yuzisun yes, I'll ensure the version of the KServe web app will be working as expected with the version of KServe that will be included. Thanks for confirming as well!

Since there are no concerns raised for the above timeline we will go forth and finalize it. Happy to discuss if anything unexpected turns up though. We will also send an email in the mailing list to announce this finalized schedule.

/lgtm
/approve

**Comment by annajung** [comment]
@jbottum It's been updated https://github.com/kubeflow/community/pull/549 by @kimwnasptd

**Pull request merged**
