### PR TITLE
Update calendar.yaml

### PR DESCRIPTION
**Pull request by Swikar**

### CODE REVIEW

**Comment by jlewi** [comment]
@karlschriek should review

**Comment by jlewi** [comment]
@karlschriek Could you please review this PR?

**Comment by jlewi** [comment]
@karlschriek ping?
/assign @jtfogarty

**Comment by Swikar** [comment]
@karlschriek can you review this?

**Comment by karlschriek** [comment]
@yuzliu could you perhaps confirm again which one is the correct meeting room? https://meet.google.com/dxz-zthy-xjn or https://meet.google.com/efi-tdbx-owi?

https://meet.google.com/dxz-zthy-xjn is currently in the calendar. If you still have access to that room I would prefer to use it.

**Comment by yuzliu** [comment]
> @yuzliu could you perhaps confirm again which one is the correct meeting room? https://meet.google.com/dxz-zthy-xjn or https://meet.google.com/efi-tdbx-owi?
> 
> https://meet.google.com/dxz-zthy-xjn is currently in the calendar. If you still have access to that room I would prefer to use it.

Hi https://meet.google.com/dxz-zthy-xjn works, we can continue to use this room.

**Comment by karlschriek** [comment]
Ok then I think we can close this PR

**Pull request closed without merging**
