### PR TITLE
Jeffwan@ step down and nominate PatrickXYS@ to represent AWS

### PR DESCRIPTION
**Pull request by Jeffwan**
As you know that I left AWS and join ByteDance recently. I make this change to 

1. Remove myself from WG-deployment and WG-manifest. I am still working in WG-training and some subprojects. 
2. Nominate @PatrickXYS as a lead of WG-deployment. Most AWS Kubeflow users are using kfctl and Yao spend lots of time on tooling to improve user experience. 

/cc @kubeflow/wg-deployment-leads @kubeflow/wg-manifests-leads
/cc @PatrickXYS 

@PatrickXYS will be the primary contact for any AWS issues and he will represent AWS in the community.  Yao started to contribute to Kubeflow early this year and participate actively in the community to help users resolve issues. 
/cc @kubeflow/wg-pipeline-leads  @kubeflow/wg-automl-leads @kubeflow/wg-notebook-leads @kubeflow/wg-serving-leads

### CODE REVIEW

**Comment by PatrickXYS** [comment]
@Jeffwan Thanks for your contributions! Will keep going as always

**Comment by ellistarn** [comment]
+1. Thank you to both @Jeffwan and @PatrickXYS for your operational excellence contributions across Kubeflow!

**Comment by Bobgy** [comment]
+1 Great contributions and looking forward to future cooperations with you.

**Review by gaocegege — COMMENTED** [review]
/lgtm

**Comment by PatrickXYS** [comment]
This has been more than one week, can we move forward?

**Pull request merged**
