### PR TITLE
Add Yuki to wgs.yaml

### PR DESCRIPTION
**Pull request by johnugeorge**
Update wgs.yaml to reflect the leads group members
Related: https://github.com/kubeflow/internal-acls/pull/668

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
/hold 
for other leads.

**Comment by tenzen-y** [comment]
cc: @kubeflow/wg-automl-leads @kubeflow/wg-training-leads

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Review by andreyvelich — COMMENTED** [review]
@johnugeorge I think, you should run `make generate` as outlined here: https://github.com/kubeflow/community/tree/master/generator#how-to-use to update all assets.

**Review by andreyvelich — APPROVED** [review]
Thanks for the update!
/lgtm
/approve

**Pull request merged**
