### PR TITLE
Update join Slack link to the non expiring link

### PR DESCRIPTION
**Pull request by mameshini**

### CODE REVIEW

**Comment by jbottum** [comment]
/lgtm

thanks!

**Comment by thesuperzapper** [comment]
@mameshini @jbottum can we please update it to `https://www.kubeflow.org/docs/about/community/#kubeflow-slack` (rather than using the invited link directly).

As I was saying in https://github.com/kubeflow/community/issues/602#issuecomment-1411298281, if we change how we do Slack inviting in the future, we will forget about this link otherwise.

**Comment by Syulin7** [comment]
> @mameshini @jbottum can we please update it to `https://www.kubeflow.org/docs/about/community/#kubeflow-slack` (rather than using the invited link directly).
> 
> As I was saying in [#602 (comment)](https://github.com/kubeflow/community/issues/602#issuecomment-1411298281), if we change how we do Slack inviting in the future, we will forget about this link otherwise.

Agree. I would like to update it.

**Comment by mameshini** [comment]
Updated and merged [#605] into master

**Pull request merged**
