### PR TITLE
change Community Meeting to weekly

### PR DESCRIPTION
**Pull request by jbottum**
change Kubeflow Community Meeting to weekly on every Tuesday.

### CODE REVIEW

**Review by andreyvelich — COMMENTED** [review]
Thank you for this update @jbottum
/lgtm
/assign @james-jwu @theadactyl

**Comment by james-jwu** [comment]
@jbottum @andreyvelich Was this change discussed in Kubeflow community meeting? I did not find any mention of this change in meeting notes. Just want to double check.

**Comment by andreyvelich** [comment]
@james-jwu yes, you can see the recording here: https://youtu.be/_LmQbnAmlqY

**Pull request merged**
