### PR TITLE
PatrickXYS@ step down

### PR DESCRIPTION
**Pull request by PatrickXYS**
Since recently I left AWS and joined Google, I won't be working on the kubeflow manifests and deployment areas. 

I made the change to remove myself from co-leader of WG-manifests and WG-deployment.

It's been a great journey working with all of kubeflow community folks!

/cc @kubeflow/wg-manifests-leads  @kubeflow/wg-deployment-leads @kubeflow/wg-notebooks-leads  @kubeflow/wg-serving-leads  @kubeflow/wg-training-leads @kubeflow/wg-automl-leads @kubeflow/wg-pipeline-leads

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
Congrats and good luck!
/lgtm

**Comment by PatrickXYS** [comment]
@googlebot I fixed it.

**Comment by PatrickXYS** [comment]
@googlebot I fixed it.

**Comment by thesuperzapper** [comment]
@PatrickXYS I am very saddened to see you go, the community will sorely miss you.

Hopefully, there is opportunity for you to contribute to Kubeflow again in the future!

**Comment by kimwnasptd** [comment]
It was really nice working with you and thank you very much for all the effort and help you've provided! You've really left a mark and shaped how we run our tests in Kubeflow.

Best of luck with your next steps, I'm sure you'll do great!

**Comment by Jeffwan** [comment]
@PatrickXYS Thanks for all your contribution and good luck on your next journey! 

You can edit commit author to your original email to pass CLA check.

**Comment by gaocegege** [comment]
@PatrickXYS Thanks for your contribution! 

Enjoy the new job and grow. Good luck.

**Comment by andreyvelich** [comment]
Thank you for your great work and help @PatrickXYS.
Good luck in the new place!
/lgtm

**Comment by Bobgy** [comment]
Hi @PatrickXYS,
Thank you for all your contributions and welcome to Google! : )

===
for the CLA issue,
Did you misspell your email address in the commit?
It's `xyshoww@gmail.com`, but your github email says `xyshowww@gmail.com` (number of w is different).

**Comment by PatrickXYS** [comment]
Emmm I checked directly from xyshowww@gmail.com and tried same thing on github webpage, still failing CLA

**Comment by PatrickXYS** [comment]
@googlebot I fixed it.

**Comment by PatrickXYS** [comment]
I'll create another PR afterwards

/close

**Pull request closed without merging**
