### PR TITLE
propopsal: Add MXNet

### PR DESCRIPTION
**Pull request by gaocegege**
/assign @jlewi 

Ref #136 

/cc @brucechin

@brucechin is interested in implementing mxnet operator for kubeflow community

Signed-off-by: Ce Gao <gaoce@caicloud.io>

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/137)

### CODE REVIEW

**Comment by jlewi** [comment]
@brucechin are you the only one that's going to be working on the MXNet operator?

**Comment by gaocegege** [comment]
I am not sure if he is the only one, I will help him but have to give more attention to tf-operator.

**Comment by brucechin** [comment]
yeah， I'm the only one for mx operator now in my group. maybe more in the summer holiday.

**Comment by jlewi** [comment]
Is there a reason to begin working on the mxnet operator now? @brucechin do you have a specific need for mxnet or are you just looking to get involved with Kubeflow?

We already have 3 operators in progress

- TfJob
- PyTorch
- Caffe2

From a community perspective I think it would be preferable to invest more resources in getting the existing operators done before taking on more operators.

Building these operators is proving to be fairly expensive. The TFJob operator has been in development for almost a year and had significant contributions from over 6 people.

Ideally, if we do want to support more operators, I think we might want to consider how to build shared libraries and reuse code to reduce the cost of supporting additional frameworks.

**Comment by brucechin** [comment]
Algorithm group in my company(Tusimple) only uses MXNet, so we would like to add support for MXNet in Kubeflow. And it is important to reuse code to reduce the cost of supporting other frameworks.

**Comment by gaocegege** [comment]
Personally, I agree with @jlewi . Maintaining these operators is a heavy work and I prefer to make one of these operators production ready then we could build more based on the experience we got from the previous work.

But TuSimple is using MXNet now and they are investigating using kubernetes to manage ML workloads. Then I think it also works to create a MXNet operator with the help of people in TuSimple.

WDYT?

BTW, @brucechin Do you have a plan when to use it? Maybe we could focus on tf-operator now and after the release of v0.2 I can help you to build the MXNet operator.

**Comment by jlewi** [comment]
I agree. If there is someone with a compelling need for a framework then it makes sense to support them.

Is there a way we can start trying to refactor TFJob operator code into reusable libraries to avoid duplicating the same logic for all the different operators?

**Comment by gaocegege** [comment]
@jlewi 

I think it is hard to do. There are some operator frameworks to help programmers to create a new operator, while the code reuse is still be a problem.

Maybe we could maintain a sample controller similar to https://github.com/kubernetes/sample-controller then every operators could fork it. With such a sample controller we could make all operators in the similar architecture.

**Comment by jlewi** [comment]
I don't think there's any downside to incubating an mxnet operator.

What do others think?

**Comment by brucechin** [comment]
@gaocegege we are not in a hurry to deploy it on kubenetes now. I just need to figure out how to combine MXNet and Kubenetes in advance.

**Comment by jlewi** [comment]
@brucechin What do you think the next step should be? If you're ready to start work on an MXNET operator, I'm happy to LGTM this proposal and give you a repository to begin work.

**Comment by ankushagarwal** [comment]
I have been experimenting around with mxnet-operator here https://github.com/ankushagarwal/mxnet-operator/

Generally speaking, I am finding a lot of overlap b/w the various distributed training operators tensorflow, pytorch, mxnet, caffe2, etc. Maintaining a separate controller for each of the operators is a lot of work - and most of this work is shared b/w various operators. Some examples: PodCleanupPolicy, PodRestartPolicy, CRDValidation, Releasing, E2E Testing etc. Other than that, we are just bringing managing pods with special environment variables set.

I am currently writing a proposal which tries to abstract out the details of a specific framework and provides a single operator for all frameworks' distributed training jobs - tensorflow, pytorch, mxnet, caffe2.

**Comment by gaocegege** [comment]
@ankushagarwal 

Awesome idea. I am looking forward to your proposal. We have lots of operators. If we could maintain one for all, it will be better. I had the same idea before, while I find that caffe2 requires backend and does not has the similar pattern compared with tf.

**Comment by jlewi** [comment]
@brucechin @gaocegege What's the status of this? Is anyone working on mxnet?

**Comment by wsxiaozhang** [comment]
A MXNet operator would be good before we having some generic pattern operators like PSOperator, MPIOperator, etc.  I know someone is planning to contribute a MXNet operator. I'll introduce him here.

**Comment by gaocegege** [comment]
@jlewi 
Could we merge the PR or close it? MXNet operator is existed now and upgrading to v1alpha2.

**Comment by jlewi** [comment]
I think we should close it rather than merge it because I don't know how relevant the technical details are e.g. I think @suleisl2000 already started changing the APi to be compatible with our v1alpha2 APIs. 

My suggestion would be to close it and then at some point we can create a more up to date doc describing the actual implementation.

@gaocegege  @suleisl2000 WDYT?

**Comment by gaocegege** [comment]
SGTM

**Pull request closed without merging**
