### PR TITLE
Adding a Kubeflow presentation template in pptx and odp

### PR DESCRIPTION
**Pull request by castrojo**
Konstantinos Palaiologos was kind enough to generate a nice presentation template for Kubeflow for people who are doing Kubeflow presentations. I thought it'd be cool to host these in a place where they can be shared/improved on by everyone. 

Reviewers, let me know if you think they should live someplace else if you'd prefer to not have a new directory in the root. Thanks!

### CODE REVIEW

**Comment by theadactyl** [comment]
How can I best view the template deck? I believe we have an existing template in the community drive, and am wary of producing an "official" Kubeflow template.

**Comment by thesuperzapper** [comment]
No comment on the template itself, but if you make a new folder, please create an OWNERS file

**Comment by castrojo** [comment]
@theadactyl I wasn't aware there was a google drive, any way I can check it out? The pptx and odp can open in any presentation software, and can also be imported into google docs.

**Comment by theadactyl** [comment]
All kubeflow-discuss members have access to the shared drive.

**Comment by theadactyl** [comment]
View access that is.

**Pull request closed without merging**
