### PR TITLE
Put calendar events in code

### PR DESCRIPTION
**Pull request by scottilee**
This puts calendar events for the [Kubeflow calendar](https://calendar.google.com/calendar/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428%40group.calendar.google.com&ctz=America%2FLos_Angeles) in YAML so they can be defined and updated in one place.

The associated Python script parses the YAML and creates the events on a Google calendar.

This is in reference to https://github.com/kubeflow/community/issues/274.

@jlewi I need your help modifying this so it works with Prow or some CI to automatically update the calendar as well as associated things like hooking it up to the Kubeflow calendar. And of course, the code could be better so I'd appreciate comments on that as well.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/283)

### CODE REVIEW

**Comment by jlewi** [comment]
Thanks @scottilee Can you update the PR description with a link to the github issue that is tracking putting the calendar events in YAML?

**Comment by scottilee** [comment]
> Thanks @scottilee Can you update the PR description with a link to the github issue that is tracking putting the calendar events in YAML?

Done.


> > ```python
> > def main():
> >   flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
> > ```
> 
> Did you try this out? What if a human is running the script; is it possible to direct the user through the OAuth web flow?

Yes, I tried it and it works. If it's run manually it does direct you to the OAuth web flow. I think I need to change it so it doesn't direct to a web flow for CICD purposes. Maybe something like https://stackoverflow.com/questions/41204071/how-to-authorize-a-python-google-api-client-service-given-an-oauth2-access-token.


> Can we use the Google Application Default Credentials Flow;
> see here
> https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-python
> 
> Normally with Google Cloud APIs you can just create a client and it will automatically try a variety of methods to get a credential until it finds a credential that works.
> 
> The non Cloud APIs might work a little bit differently?

Yes, I think the non-Cloud APIs work differently. From the examples I've seen, the credentials are provided explicitly.


> > ```python
> >       rec = 'RRULE:FREQ={};BYDAY={}'.format(meeting['frequency'].upper(), day_of_week)
> > 
> >       if meeting['frequency'] == "bi-weekly":
> > ```
> 
> What are the replacements here for?

They update the RRULE (meeting recurrence). The default recurrence for a meeting is set to weekly but of course it can be every other week or once a month.

**Comment by jlewi** [comment]
Thanks.

Couple minor comments but overall looks good.

Can you update the isssue #274 with the steps required to get this working; e.g.

* How we can automatically run it on post-submit so that we update the calendar after each change
* How we go about provisioning credentials in the test cluster that this script can use

**Comment by scottilee** [comment]
> Thanks.
> 
> Couple minor comments but overall looks good.
> 
> Can you update the isssue #274 with the steps required to get this working; e.g.
> 
> * How we can automatically run it on post-submit so that we update the calendar after each change
> * How we go about provisioning credentials in the test cluster that this script can use

I'll need your help with this. Currently, the script requires the user to visit a URL to authorize the application. I think the way around this is to use a service account (https://developers.google.com/identity/protocols/OAuth2ServiceAccount). If that is possible I can set up a post-submit job to run.

**Comment by jlewi** [comment]
@scottilee yes I believe service account is the way we want to go. Lets use the issue to track and figure out what needs to be done.

**Comment by jlewi** [comment]
@scottilee Looks like there are a couple unaddressed comments could you PTAL and then we  can close this out.

**Comment by scottilee** [comment]
@jlewi I added logging and added more calendar events.

**Pull request merged**
