### PR TITLE
update members.yaml

### PR DESCRIPTION
**Pull request by wangkeqiang123**
add personal info

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/219)

### CODE REVIEW

**Comment by wangkeqiang123** [comment]
I signed it!

**Comment by jlewi** [comment]
@wangkeqiang123 Thanks for thinking about joining the community.

Have you started contributing to the community yet? If not would you mind making a couple contributions first.

There's a variety of ways to contribute.
* Fix a couple issues; e.g. bug fixes; doc cleanup etc...
* Answer questions on GitHub or slack
* Try out Kubeflow and file issues for any problems you encounter.

**Comment by wangkeqiang123** [comment]
I have closed this PR.

**Pull request closed without merging**
