### PR TITLE
add yuvipanda to jupyter org and members list

### PR DESCRIPTION
**Pull request by willingc**
cc @yuvipanda :sunny:

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/103)

### CODE REVIEW

**Comment by jlewi** [comment]
@yuvipanda Would you mind "/lgtm" this? Just so we have a clear record.

**Comment by texasmichelle** [comment]
This looks good to go as soon as the conflict is resolved.

**Comment by texasmichelle** [comment]
ping @yuvipanda for an LGTM & rebase

**Comment by yuvipanda** [comment]
Sorry, this slipped my radar. I don't believe I've the permissions to rebase or merge these conflicts.

/lgtm

**Comment by texasmichelle** [comment]
/approve

Heads up that this file will likely be removed soon: #218 

Instructions [here](https://github.com/kubeflow/website/pull/334) on how to join the GitHub org.

**Pull request merged**
