### PR TITLE
docs: correct RC.0 release date

### PR DESCRIPTION
**Pull request by DnPlas**
Correcting RC.0 release date to be the same as the week when we finish manifests sync.

### CODE REVIEW

**Comment by jbottum** [comment]
should we adjust the date or just post it?

**Comment by DnPlas** [comment]
> should we adjust the date or just post it?

sorry, which date? @jbottum

**Comment by jbottum** [comment]
- **Wednesday, Aug 16th 2023**  : Week 15 C\* - Manifests sync ends, RC.0 is cut, manifests testing and bug fixing starts
- **Wednesday, Aug 23rd 2023**  : Week 16     - Manifests testing and bug fixing ends, distribution testing starts

**Comment by DnPlas** [comment]
> * **Wednesday, Aug 16th 2023**  : Week 15 C* - Manifests sync ends, RC.0 is cut, manifests testing and bug fixing starts
> 
>     * **Wednesday, Aug 23rd 2023**  : Week 16     - Manifests testing and bug fixing ends, distribution testing starts

Yes I will have to change that, I'll wait just a bit to confirm these dates before sending another commit. Thanks for noticing @jbottum

**Comment by zijianjoy** [comment]
/lgtm
/approve

Thank you @DnPlas !

**Pull request merged**
