### PR TITLE
Simple update to versioning of Manifests/Notebooks

### PR DESCRIPTION
**Pull request by jbottum**
This is a simple documentation update to provide an explanation of the versioning process for the Manifests and Notebook Working Groups, which follow the general Kubeflow release process and is defined in the Kubeflow Release handbook.

### CODE REVIEW

**Comment by jbottum** [comment]
@kimwnasptd @annajung is this an acceptable (simple) update for the Manifest and Notebook WG documentation ?

**Comment by jbottum** [comment]
related to https://github.com/kubeflow/community/pull/601

**Comment by annajung** [comment]
closing in favor of https://github.com/kubeflow/community/pull/613
/close

**Pull request closed without merging**
