### PR TITLE
Working Group list - fix template to remove duplicated list and empty lists

### LINKED ISSUE #508: Working Group list - duplicated list and empty lists
The [wg-list.md](https://github.com/kubeflow/community/blob/master/wg-list.md) file has a few issues that I think are related to it being copied over from Kubernetes, which has SIGs, WGs, UGs, and Committees.

Here are the specific issues:
* Title is currently "SIGs and Working Groups" but should probably just be "Working Groups"
* The first sentence mentions SIGs.
* The WGs are listed twice - under the heading "Master WG List" and "Master Working Group List"
* There are empty tables for "Master User Group List" and "Master Committee List"

I dug into this a little bit, since I'm familiar with how k8s did this, and I think all of these issues can probably be fixed in this template file: https://github.com/kubeflow/community/blob/master/generator/list.tmpl 

One other issue is that 
* There is a comment in [wg-list.md](https://github.com/kubeflow/community/blob/master/wg-list.md) file that reads "To understand how this file is generated, see https://github.com/kubeflow/community/generator/README.md", but that link 404s. I think it should be "https://github.com/kubeflow/community/blob/master/generator/README.md"

I think this can be fixed in the header file here: https://github.com/kubeflow/community/blob/master/generator/header.tmpl

I'm happy to fix these if someone can confirm that these are the correct places for those fixes. But also haven't used my local Go env in ages and would need to update it, so if someone else wanted to do it, that would be fab :) 

Tagging @castrojo since he's familiar with this from k8s and it looks like @swiftdiaries ported this over and might know more.

### PR DESCRIPTION
**Pull request by geekygirldawn**
Fixes to remove SIG, UG, and other mentions out of the wg generation templates that were a carryover from when these were migrated over from k8s. I also fixed the broken link containing the instructions for building the file.

This fixes #508.

### CODE REVIEW

**Comment by geekygirldawn** [comment]
Since this hadn't been reviewed / merged, I went ahead and cleaned up the SIG data and added it to wg-list.md. Everything looks good in the generated files, so this is ready to merge.

**Review by swiftdiaries — APPROVED** [review]

**Comment by Bobgy** [comment]
/lgtm
Thank you @geekygirldawn!
This looks great to me.

/assign @theadactyl 
probably you want to have a look?

**Comment by theadactyl** [comment]
Looks great! Thanks for this @geekygirldawn 

/approve

**Comment by Bobgy** [comment]
Hi, can you remove @catblade, @tbaums from OWNER_ALIASES first to get the PR merged?
https://github.com/kubeflow/community/pull/509#issuecomment-823882253

**Comment by geekygirldawn** [comment]
Hi @Bobgy - I removed @catblade and @tbaums from wgs.yaml, which also removes them from the owners file and the SIG README to allow this to be merged.

@castrojo This reverts some of the work in the PR when you added them. We can add them back to wgs.yaml after org ownership is sorted out.

**Pull request merged**
