### PR TITLE
Add kimwnasptd to manifests wg

### PR DESCRIPTION
**Pull request by yanniszark**
Opening a PR to add @kimwnasptd as a lead for wg-manifests.
From Arrikto, @vkoukis will be stepping down as a lead and be replaced by @kimwnasptd.
@kimwnasptd already has major contributions across many WGs and has helped me a lot during the release, so I think he will be a great addition to the WG.

cc'ing @kubeflow/wg-manifests-leads

### CODE REVIEW

**Review by PatrickXYS — APPROVED** [review]
@kimwnasptd Nice to have you as part of WG manifest!

**Comment by vkoukis** [comment]
Looking forward to having @kimwnasptd as a wg-manifests lead! he has a proven track record with Kubeflow and can't wait to see him contribute even more.

/lgtm

**Comment by yanniszark** [comment]
cc @Bobgy who has the permissions to merge.
Is there anything else remaining in order for this PR to be merged, since the majority of leads have agreed?
@StefanoFioravanzo is on PTO right now, but I don't believe he'll have an issue with this.

**Comment by Bobgy** [comment]
/approve
Sorry for the delay!
Looking forward to working with you too @kimwnasptd!

**Comment by StefanoFioravanzo** [comment]
I am late to the party, but of course I am happy so see @kimwnasptd be part of the Manifests WG!

**Pull request merged**
