### PR TITLE
Add 1.9 Release Schedule Timeline

### PR DESCRIPTION
**Pull request by rimolive**
Close kubeflow/manifests#2606

### CODE REVIEW

**Comment by jbottum** [comment]
I would consider 

adding Week 7 - Checkpoint - Development should be 50%+.   Also a checkpoint on initial docs and test plan

removing most of the actual dates and just leave the week numbers.     You might leave a few dates...maybe leave Week 7 (Checkpoint), Week 13 (Feature Freeze), Week X (Distribution Testing), Week Y (Release).

**Comment by rimolive** [comment]
@jbottum I added this PR for reference but we're still reviewing the dates until roadmap track issues be finished. We'll consider your comments as well.

**Comment by rimolive** [comment]
@jbottum @DnPlas May I have any of you to lgtm/approve?

**Comment by rimolive** [comment]
@zijianjoy Could you please approve this?

**Comment by rimolive** [comment]
@jbottum Looke like you're the only one who can approve

**Pull request merged**
