### PR TITLE
Add xieydd and pineking as member

### PR DESCRIPTION
**Pull request by xieydd**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/217)

### CODE REVIEW

**Comment by jlewi** [comment]
https://devstats.kubeflow.org/d/13/developers-table?orgId=1

xieydd 14 Prs

Looks like pineking has been very active in discussions on GitHub issues
https://github.com/issues?q=org%3Akubeflow+pineking+is%3Aclosed

Thank you both very much for your contributions.

/lgtm
/approve

**Comment by jlewi** [comment]
Please submit a PR to
Adding yourself as members so we can send you an invite to own the org.
https://github.com/kubeflow/internal-acls/blob/master/github-orgs/kubeflow/org.yaml

**Comment by xieydd** [comment]
@jlewi Done, pls help to review this [PR](https://github.com/kubeflow/internal-acls/pull/31).

**Comment by xieydd** [comment]
@jlewi . I notice the [PR](https://github.com/kubeflow/internal-acls/pull/31) is merged, but i did`t receive the inventation of the org. 😝

**Pull request merged**
