### PR TITLE
Update members.yaml

### PR DESCRIPTION
**Pull request by animeshsingh**
Need it for the work we are doing with Kubeflow and related contributions

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/241)

### CODE REVIEW

**Comment by jlewi** [comment]
If you want to join the github org you should follow the contributing guide. This isn't is the right file.
https://www.kubeflow.org/docs/about/contributing/#joining-the-kubeflow-github-org

**Comment by animeshsingh** [comment]
Thanks @jlewi . Have done a PR on the org.yaml. Please take a look
https://github.com/kubeflow/internal-acls/pull/68

**Pull request merged**
