### PR TITLE
Add Uber to member organizations

### PR DESCRIPTION
**Pull request by jiezhang**
* Per our legal team, please inform us if/when Kubeflow starts using this list for more than attributing to the contributors.
* Please also note that we are not authorizing Kubeflow any right to use Uber’s name and logo in any of its promotion material.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/116)

### CODE REVIEW

**Comment by jiezhang** [comment]
@jlewi Can you please also add @alsrgv as kubeflow members?

**Comment by jlewi** [comment]
If you don't want Uber's name to be included in promotional materials e.g. mentions at Kubecon about participating organizations then you shouldn't add Uber to member_organizations.yaml.

The primary purpose of this file is to keep track of companies that would like to be acknowledged as being part of Kubeflow.

**Comment by jlewi** [comment]
Sent @alsrgv an invite.

**Comment by jlewi** [comment]
SGTM.

**Comment by alsrgv** [comment]
@jlewi, as discussed offline, we're fine with being on the list as long as we can remove ourselves if needed.

**Comment by jlewi** [comment]
Yup just submit a PR.

/lgtm
/approve

**Pull request merged**
