### PR TITLE
Add link to allreduce introduction.

### PR DESCRIPTION
**Pull request by rongou**
/assign @gaocegege

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/141)

### CODE REVIEW

**Comment by gaocegege** [comment]
/lgtm
/approve
Thanks!

**Comment by gaocegege** [comment]
/assign @jlewi 

I am not the approver of the repository then we need your approval.

**Comment by gaocegege** [comment]
Hi @rongou 

When will you begin to work on the awesome operator? We could create a new repo for it and setup the CI before that.

**Comment by rongou** [comment]
The code is actually mostly there, I just need to do some renaming. Where should this live? https://github.com/kubeflow/mpi-operator? @jlewi?

**Comment by jlewi** [comment]
Name SGTM. @rongou Can you open up a PR to create/transfer the repository.

/approve

**Comment by ankushagarwal** [comment]
https://github.com/kubeflow/community/issues might be a better place to create a PR to request create/transfer of the new repo

**Comment by rongou** [comment]
Thanks! Done: https://github.com/kubeflow/community/issues/143

**Pull request merged**
