### PR TITLE
Create the 1.9 Release team document

### PR DESCRIPTION
**Pull request by rimolive**
Close kubeflow/manifests#2604

### CODE REVIEW

**Comment by jbottum** [comment]
this is great.   thanks.

**Comment by jbottum** [comment]
we need to think about what happens if dates change.    Do we just leave it or do we spend time updating.    typically we done have cycles to modify.

**Comment by rimolive** [comment]
@jbottum I made a change in this PR and will only add the release team members for now. I'll be working on a separate one for the release schedule when we get the roadmaps finished.

**Comment by StefanoFioravanzo** [comment]
Can we officially include Diego and Helber even though they are not part of the GH organization?

**Comment by rimolive** [comment]
@zijianjoy Correct me if I'm wrong, but I was supposed to merge this PR since I'm in the @kubeflow/release-managers group. Right?

**Comment by zijianjoy** [comment]
/approve

@rimolive Happy to help merging this PR.

**Comment by rimolive** [comment]
@jbottum We need your approval, if you are good with the release team members table.

**Comment by kimwnasptd** [comment]
Looking forward to next steps!

/lgtm
/approve

**Pull request merged**
