### PR TITLE
Add aws to org and member

### PR DESCRIPTION
**Pull request by Jeffwan**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/253)

### CODE REVIEW

**Comment by abhi-g** [comment]
Welcome @Jeffwan! Can you please attach any PRs that you might have merged to Kubeflow as a support for the membership. Please see [Contributing Guidelines](https://www.kubeflow.org/docs/about/contributing/#joining-the-community)

**Comment by jlewi** [comment]
@Jeffwan has worked on kfctl.sh to support AWS and some other fixes for AWS
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3AJeffwan+org%3Akubeflow

@abhi-g  I believe he's planning on working on porting AWS support to kfctl.

**Comment by abhi-g** [comment]
Awesome! Thanks for the info.

/ok-to-test

/lgtm
/approve

**Comment by Jeffwan** [comment]
@abhi-g @jlewi 
Thanks a lot! The next step is to move existing aws provision process to kfctl (golang).  At the same time, I am working on adding more runners and examples to pipeline. 

For 0.6, 
I will try to work with kubeflow team together on istio migration, right now, we use ingress and cloud solutions to deal with authentication and TLS support. I think we can provide more feedbacks here and make sure we move to same direction. 
Another thing is to manage user permission in kubernetes native way. One of a AWS team is also helping to add more features to mxnet-operator.

**Pull request merged**
