### PR TITLE
bumping the name to appear in organizers list

### PR DESCRIPTION
**Pull request by animeshsingh**
cc @Bobgy

### CODE REVIEW

**Comment by thesuperzapper** [comment]
@theadactyl we need someone to `/aprove` this (who is a root OWNER) as @Bobgy is away, can you do it?

/lgtm

**Comment by Bobgy** [comment]
Hi @animeshsingh,
Promoting you to a chair would require process in https://github.com/kubeflow/community/blob/master/wgs/wg-governance.md#on-boarding-and-off-boarding-leads.

Without such a change, I think we can change README generation script to include all TLs in the contact page too
https://github.com/kubeflow/community/blob/cf493cc9eb1e00216a4b01d7e2af0ba0ded0debf/generator/wg_readme.tmpl#L31

What do you think?

**Comment by animeshsingh** [comment]
@Bobgy whatever is fastest for you to get this moving.

**Comment by Bobgy** [comment]
Understood, the change generation script route is faster.

**Comment by animeshsingh** [comment]
@Bobgy so you are going to tackle that?

**Comment by Bobgy** [comment]
I can help with review and approval. : )

**Comment by jlewi** [comment]
Can we close this PR?

**Comment by Bobgy** [comment]
Thanks for the reminder!
/close

**Pull request closed without merging**
