### PR TITLE
Merge security and manifests WG meeting in a cal entry

### PR DESCRIPTION
**Pull request by rimolive**

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
CC @kimwnasptd @akgraner for review

**Comment by juliusvonkohout** [comment]
@kimwnasptd are you alright with the organizer change and should we switch to the new Zoom as well?

**Review by thesuperzapper — CHANGES_REQUESTED** [review]
As it says at the top of this file, never remove a recurring meeting from this file otherwise it will end up in the calendar forever. 

You have to move it to the legacy section and set its end date in the past.

**Comment by rimolive** [comment]
> As it says at the top of this file, never remove a recurring meeting from this file otherwise it will end up in the calendar forever.
> 
> You have to move it to the legacy section and set its end date in the past.

My apologies to that. I made the changes as requested.

**Comment by rimolive** [comment]
cc @kubeflow/kubeflow-steering-committee @juliusvonkohout @kimwnasptd

**Comment by juliusvonkohout** [comment]
/lgtm

I will probably add the new zoom bridge in a follow up PR.

**Comment by thesuperzapper** [comment]
I just saw that the proposed meeting is named `Kubeflow Platform Meeting (Manifests + Security WG)`.

It's hard to imagine that "Kubeflow Platform" should not also involve the distribution owners? I am not sure we should be calling the meetings "Kubeflow Platform" if they are only referring to Manifests/Security WGs.

**Comment by juliusvonkohout** [comment]
> I just saw that the proposed meeting is named `Kubeflow Platform Meeting (Manifests + Security WG)`.
> 
> It's hard to imagine that "Kubeflow Platform" should not also involve the distribution owners? I am not sure we should be calling the meetings "Kubeflow Platform" if they are only referring to Manifests/Security WGs.

Then lets ask @andreyvelich @terrytangyuan @jbottum what they think. Based on what they decide we could change it.

**Comment by andreyvelich** [comment]
From my perspective, this meeting should be the main place for users if they have questions related to Kubeflow Platform components. For example, questions about Profile Controller, KFAM, Central Dashboard, etc.

Distributions should certainly join these calls since they are main consumers of Kubeflow Manifests.

**Comment by juliusvonkohout** [comment]
> From my perspective, this meeting should be the main place for users if they have questions related to Kubeflow Platform components. For example, questions about Profile Controller, KFAM, Central Dashboard, etc.
> 
> Distributions should certainly join these calls since they are main consumers of Kubeflow Manifests.

Can you approve it then or do we have to make changes?

**Review by andreyvelich — COMMENTED** [review]
/lgtm
/assign @johnugeorge @jbottum @terrytangyuan @james-jwu

**Review by terrytangyuan — APPROVED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
