### PR TITLE
Update Kubeflow 1.9 schedule

### PR DESCRIPTION
**Pull request by rimolive**

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
I bet that July 22 for the final release is more realistic. We still need to get the final releases from almost all working groups, especially kubeflow/kubeflow and there is

- Merge  https://github.com/kubeflow/manifests/pull/2751 and https://github.com/kserve/models-web-app/pull/81 https://github.com/kubeflow/manifests/pull/2752
- The final releases for kubeflow/kubeflow, training operator, Katib. What is the status there?
- For pipelines we need to fix https://github.com/kubeflow/manifests/issues/2747 via https://github.com/kubeflow/manifests/pull/2753
- https://github.com/kubeflow/manifests/pull/2667

**Comment by rimolive** [comment]
cc @jbottum care to approve?

**Comment by DnPlas** [comment]
/lgtm

@jbottum @kimwnasptd I believe either of you can approve so we can merge this

**Comment by juliusvonkohout** [comment]
@rimolive i see

```
approvers:
  - rimolive
reviewers:
  - StefanoFioravanzo
  - hbelmiro
  - nagar-ajay
  - thesuperzapper
  - ca-scribner
  - juliusvonkohout
```

in https://github.com/kubeflow/community/blob/master/releases/OWNERS so probably you have to approve it yourself.

**Pull request merged**
