### PR TITLE
remove community meeting end-date & cleanup description

### PR DESCRIPTION
**Pull request by thesuperzapper**
This PR fixes the community meeting invites (which have expired), by making them repeat forever.

It also updates the event description to:
- be more clear
- use the international zoom links
- provide the join link for hosts (the link will only work for designated meeting hosts)

__NOTE:__ we will need a calendar admin to run `calander_import.py` to update the calendar once we merge this PR.

### CODE REVIEW

**Comment by thesuperzapper** [comment]
/assign @james-jwu @zijianjoy @jbottum 

We currently have no calendar invite for the community meetings, can we merge this ASAP?

Also, if you are a calendar admin can you please run `calander_import.py` (see [README](https://github.com/kubeflow/community/tree/master/calendar)) after we merge, as I believe syncing will not be automated anymore.

**Comment by thesuperzapper** [comment]
Looks like the event was updated after this was merged, not sure if someone manually ran the sync, or if there is some mystical controller running somewhere.

**Comment by zijianjoy** [comment]
Calendar is automatically synced on master branch.

**Pull request merged**
