### PR TITLE
manifests: Update charter for leadership roles

### PR DESCRIPTION
**Pull request by kimwnasptd**
Since we've gotten to agreement on https://github.com/kubeflow/manifests/pull/2452 I'm submitting this PR here, since it's where it needs to be merged.

I also added a small part from the pipelines wg as well regarding position swapping by people in the same organisation.
https://github.com/kubeflow/community/blob/master/wg-pipelines/charter.md

/cc @kubeflow/wg-manifests-leads @annajung @juliusvonkohout @jbottum

### CODE REVIEW

**Comment by james-jwu** [comment]
Before I merge this, can I get one lgtm from someone in the manfest WG?

**Comment by annajung** [comment]
This was discussed during one of the past Manifest WG meetings and active WG members discussed and agreed on the proposed.

/lgtm

**Pull request merged**
