### PR TITLE
add zabbasi to approvers

### PR DESCRIPTION
**Pull request by zabbasi**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/252)

### CODE REVIEW

**Comment by abhi-g** [comment]
@zabbasi please see #251 to prune reviewers. Are you sure you meant to add owner for this repository

**Comment by zabbasi** [comment]
> @zabbasi please see #251 to prune reviewers. Are you sure you meant to add owner for this repository

 to review/approve #249 which is assigned to me.

**Comment by abhi-g** [comment]
Okay, please add yourself to reviewers in that case. Given Jeremy's cleanup, I'd like to avoid adding too many approvers for this repo.

**Pull request merged**
