### PR TITLE
Proposal for triaging GitHub issues

### PR DESCRIPTION
**Pull request by jlewi**
Related to: kubeflow/community#280

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/community/281)

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @theadactyl 
/assign @abhi-g 
/assign @texasmichelle 
/assign @kkasravi 
/assign @ddutta 
/assign @pdmack 

Thoughts?

**Comment by jlewi** [comment]
@elviraux @jbottum @abhi-g @kkasravi Anyone interested in looking at this and commenting?

**Comment by kkasravi** [comment]
I think it’s needed, though there are also many issues/questions raised in slack channels. Should the triage be subdivided into topics and expanded to include monitoring slack channels?

**Comment by jlewi** [comment]
@kkasravi I think we should try to get a handle on GitHub first. For other channels and slack in particular I think we will probably want to try to push issues that take time to resolve into GitHub issues; otherwise I'm not sure how we will track them.

**Comment by jlewi** [comment]
Notebook to compute statistics and see how we are doing is in
https://github.com/kubeflow/code-intelligence/pull/32

And here's a plot
triaged

**Comment by jlewi** [comment]
@abhi-g @theadactyl We've published this at a couple community meetings and haven't gotten many comments. So I think by lazy consensus this is approved.

Would one of you mind LGTM'ing this please?

**Pull request merged**
