### PR TITLE
update manifests wg readme

### PR DESCRIPTION
**Pull request by juliusvonkohout**
@andreyvelich @kimwnasptd 

as requested in https://github.com/kubeflow/website/pull/3724#issuecomment-2109632467

### CODE REVIEW

**Comment by juliusvonkohout** [comment]
@kubeflow/kubeflow-steering-committee

**Review by andreyvelich — COMMENTED** [review]
Thanks for updating Manifests WG readme.

You might need to update the wgs.yaml like in this PR: https://github.com/kubeflow/community/pull/713 and run [generator to re-create the README.](https://github.com/kubeflow/community/tree/master/generator).

CC current Manifests WG Leads.

/assign @yanniszark @kimwnasptd @elikatsis @StefanoFioravanzo @PatrickXYS

**Comment by juliusvonkohout** [comment]
@andreyvelich @james-jwu  i hope it is correct now and also in synchronization with https://github.com/kubeflow/manifests/pull/2629

**Comment by juliusvonkohout** [comment]
@StefanoFioravanzo can you give an explicit /lgtm again despite https://github.com/kubeflow/manifests/pull/2629#issuecomment-1970008996

**Pull request merged**
