### PR TITLE
Add SIG onprem to wgs.yaml and add a draft charter.

### PR DESCRIPTION
**Pull request by castrojo**
SIG Onprem has consensus on a draft charter and would like to proceed as a SIG in Kubeflow.

### CODE REVIEW

**Comment by castrojo** [comment]
@googlebot I signed it!

**Comment by castrojo** [comment]
@googlebot I signed it!

**Comment by castrojo** [comment]
@googlebot I signed it!

(Sorry for the spam everyone, think I got it this time.)

**Comment by jlewi** [comment]
@kubeflow/project-steering-group

**Comment by thesuperzapper** [comment]
@theadactyl we actually need you to do `/aprove`

**Comment by theadactyl** [comment]
ah thanks!  

/approve

**Pull request merged**
