### PR TITLE
Update the 1.6 release timeline

### PR DESCRIPTION
**Pull request by annajung**
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>

During the distribution testing phase, a [release-blocking issue](https://github.com/kubeflow/kubeflow/issues/6572#issuecomment-1194513442) was identified. This PR updates the 1.6 release timeline to extend the release for the release-blocking issue to be resolved with extra time for distribution to test and docs to be updated. Details on the current release status can be found on the [distribution tracking issue](https://github.com/kubeflow/manifests/issues/2221#issuecomment-1211081904)

This PR updates the release timeline with the following schedule:
- **Wednesday, Aug 31st 2022**: Week 25 - Distribution Testing Ends
- **Wednesday, Aug 31st 2022**: Week 25 - Docs Update Ends
- **Wednesday, Sep 7th 2022**: Week 26 - Kubeflow v1.6 Released

Note: Sep 5th is a US holiday

cc @kubeflow/release-team

### CODE REVIEW

**Comment by jbottum** [comment]
@annajung Hi Anna, thanks for moving this along.   this situation identifies a gap in our process / team construction.   we have had several delays on 1.6.   @cvenets perhaps you or someone on your team could provide a comment.   thanks!

**Comment by annajung** [comment]
@kubeflow/release-team we didn't receive any feedback on the proposed, looking for lgtm. thanks!

**Comment by kimwnasptd** [comment]
This looks good for Notebooks and Manifests, since it will give us some more time to address the reported issues in 
https://github.com/kubeflow/manifests/issues/2221#issuecomment-1211427234 
https://github.com/kubeflow/manifests/issues/2221#issuecomment-1221199387

/lgtm

**Pull request merged**
